<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nas</string>
	</array>
	<key>name</key>
	<string>Nasal</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.nasal</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.nasal</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\b[0-9]+)?\.)?\b[0-9]+([eE][-+]?[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|elsif|else)\b</string>
			<key>name</key>
			<string>keyword.control.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(while|for|foreach|forindex)\b</string>
			<key>name</key>
			<string>keyword.control.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|continue)\b</string>
			<key>name</key>
			<string>keyword.control.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(func|return|var)\b</string>
			<key>name</key>
			<string>storage.type.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(me|arg|parents)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(size|keys|append|pop|setsize|subvec|delete|int|num|streq|substr)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(chr|typeof|compile|call|die|sprintf|caller|closure|find|cmp)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(split|rand|bind|sort|ghosttype|id|readline)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rand|print|fgcommand|setprop|getprop|settimer|interpolate)\b</string>
			<key>name</key>
			<string>keyword.other.flightgear</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bmath.(sin|cos|exp|ln|sqrt|atan2|e|pi)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bbits.(sfld|fld|setfld|buf)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\butf8.(chstr|strc|substr|size|validate)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bio.(open|close|read|write|seek|tell|readln|stat)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bthread.(newthread|newlock|lock|unlock|newsem|semdown|semup)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bunix.(pipe|fork|dup2|exec|waitpid|opendir|readdir|closedir|time|chdir|environ)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bregex.(comp|exec)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bsqlite.(open|close|prepare|exec|finalize)\b</string>
			<key>name</key>
			<string>keyword.other.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nil</string>
			<key>name</key>
			<string>constant.language.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(and|or)\b)|(\+|-|%|#|\*|\/|==?|~|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.))</string>
			<key>name</key>
			<string>keyword.operator.nasal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=var)(\s*\w+)</string>
			<key>name</key>
			<string>entity.name.function.nasal</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=func)\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>variable.complex.nasal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w</string>
					<key>name</key>
					<string>variable.parameter.nasal</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nasal</string>
	<key>uuid</key>
	<string>f33e3fd8-0d8b-4e8b-b19e-54f0f4739d5a</string>
</dict>
</plist>
